### ISSUE TITLE
编译不通过。。。求助

### ISSUE THREAD

**Issue by lyglj** [jwwsjlm/TikTok_Live#1]
package command-line-arguments
        imports github.com/qtgolang/SunnyNet/SunnyNet
        imports github.com/qtgolang/SunnyNet/src/CrossCompiled: build constraints exclude all Go files in D:\goproject\pkg\mod\github.com\qtgolang\!sunny!net@v1.0.2\src\CrossCompiled
package command-line-arguments
        imports github.com/qtgolang/SunnyNet/SunnyNet
        imports github.com/qtgolang/SunnyNet/src/nfapi
        imports github.com/qtgolang/SunnyNet/src/iphlpapi: build constraints exclude all Go files in D:\goproject\pkg\mod\github.com\qtgolang\!sunny!net@v1.0.2\src\iphlpapi

**Comment by jwwsjlm** [comment]
https://github.com/qtgolang/SunnyNet
[编译请使用 TDM-GCC](https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe)
先安装tdm-gcc 然后开启gcc
