### ISSUE TITLE
可以帮看下这个错误怎么解决吗

### ISSUE THREAD

**Issue by lehun** [jwwsjlm/TikTok_Live#3]
In file included from ..\..\go\pkg\mod\github.com\qtgolang\!sunny!net@v1.0.3\src\iphlpapi\iphlpapi.go:7:
./c_iphlpapi_tcp.h:6:16: error: redefinition of 'struct _MIB_TCPROW2'
    6 | typedef struct _MIB_TCPROW2 {
      |                ^~~~~~~~~~~~
In file included from C:/msys64/mingw64/include/iprtrmib.h:16,
                 from C:/msys64/mingw64/include/iphlpapi.h:15,
                 from ./c_iphlpapi_tcp.h:2:
C:/msys64/mingw64/include/tcpmib.h:64:16: note: originally defined here
   64 | typedef struct _MIB_TCPROW2 {
      |                ^~~~~~~~~~~~
./c_iphlpapi_tcp.h:14:3: error: conflicting types for 'MIB_TCPROW2'; have 'struct _MIB_TCPROW2'
   14 | } MIB_TCPROW2, *PMIB_TCPROW2;
      |   ^~~~~~~~~~~
C:/msys64/mingw64/include/tcpmib.h:72:3: note: previous declaration of 'MIB_TCPROW2' with type 'MIB_TCPROW2'
   72 | } MIB_TCPROW2, *PMIB_TCPROW2;
      |   ^~~~~~~~~~~
./c_iphlpapi_tcp.h:14:17: error: conflicting types for 'PMIB_TCPROW2'; have 'struct _MIB_TCPROW2 *'
   14 | } MIB_TCPROW2, *PMIB_TCPROW2;
      |                 ^~~~~~~~~~~~
C:/msys64/mingw64/include/tcpmib.h:72:17: note: previous declaration of 'PMIB_TCPROW2' with type 'PMIB_TCPROW2' {aka 'struct _MIB_TCPROW2 *'}
   72 | } MIB_TCPROW2, *PMIB_TCPROW2;
      |                 ^~~~~~~~~~~~
./c_iphlpapi_tcp.h:17:16: error: redefinition of 'struct _MIB_TCPTABLE2'
   17 | typedef struct _MIB_TCPTABLE2 {
      |                ^~~~~~~~~~~~~~
C:/msys64/mingw64/include/tcpmib.h:74:16: note: originally defined here
   74 | typedef struct _MIB_TCPTABLE2 {
      |                ^~~~~~~~~~~~~~
./c_iphlpapi_tcp.h:20:3: error: conflicting types for 'MIB_TCPTABLE2'; have 'struct _MIB_TCPTABLE2'
   20 | } MIB_TCPTABLE2, *PMIB_TCPTABLE2;
      |   ^~~~~~~~~~~~~
C:/msys64/mingw64/include/tcpmib.h:77:3: note: previous declaration of 'MIB_TCPTABLE2' with type 'MIB_TCPTABLE2'
   77 | } MIB_TCPTABLE2, *PMIB_TCPTABLE2;
      |   ^~~~~~~~~~~~~
./c_iphlpapi_tcp.h:20:19: error: conflicting types for 'PMIB_TCPTABLE2'; have 'struct _MIB_TCPTABLE2 *'
   20 | } MIB_TCPTABLE2, *PMIB_TCPTABLE2;
      |                   ^~~~~~~~~~~~~~
C:/msys64/mingw64/include/tcpmib.h:77:19: note: previous declaration of 'PMIB_TCPTABLE2' with type 'PMIB_TCPTABLE2' {aka 'struct _MIB_TCPTABLE2 *'}
   77 | } MIB_TCPTABLE2, *PMIB_TCPTABLE2;
      |                   ^~~~~~~~~~~~~~
./c_iphlpapi_tcp.h:29:25: error: 'GetTcpTable2' redeclared as different kind of symbol
   29 | typedef DWORD (WINAPI * GetTcpTable2)(PMIB_TCPTABLE2 TcpTable, PULONG SizePointer, BOOL Order);

**Comment by jwwsjlm** [comment]
[安装gcc了吗](https://github.com/qtgolang/SunnyNet)
[编译请使用 TDM-GCC](https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe)
